---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL:=1h}
  url: https://oauth2-proxy.github.io/manifests
