---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: ${HAJIMARI_NAMESPACE:=hajimari}
  annotations:
    nfs.io/storage-path: "hajimari-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 128Mi
