---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: ${REFLECTOR_NAMESPACE:=reflector}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts
      chart: reflector
      version: 6.1.47
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
