---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/uptime-kuma/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: uptime-kuma
  #     namespace: uptime-kuma
  dependsOn:
    - name: settings
    - name: bjw-s-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
