---
# Wildcard certificate
# Dependencies:
# - cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wildcard-certificate
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/wildcard-certificate/certificate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: cert-manager-cluster-issuers
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
