---
# Wildcard certificate
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wildcard-certificate
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 15m
  path: ./base/wildcard-certificate/certificate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: cert-manager-issuers
  healthChecks:
    # TODO: Figure out how to use variable substitution for namespaces in here - @russell.green
    - apiVersion: v1
      kind: Secret
      name: primary-tls
      namespace: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
