---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cert-manager
  - ../../../../base/ingress-nginx
  - ../../../../base/longhorn
  - ../../../../base/kubernetes-dashboard
  - ../../../../base/cloudnative-pg
  - ../../../../base/keycloak
