---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Storage.
  - ../../../../base/nfs-subdir-external-provisioner
  - ../../../../base/primary-storage/nfs
  # Core infrastructure level.
  - ../../../../base/metallb
  - ../../../../base/kube-vip
  # Core system-level.
  - ../../../../base/reloader
  - ../../../../base/reflector
  - ../../../../base/cert-manager
  - ../../../../base/ingress-nginx
  - ../../../../base/metrics-server
  - ../../../../base/system-upgrade
  - ../../../../base/wildcard-certificate
  # Workload prerequisites.
  - ../../../../base/bjw-s
  - ../../../../base/bitnami
  # Other workloads.
  # - ../../../../base/pgadmin
  # - ../../../../base/adguard
  - ../../../../base/minio
  - ../../../../base/blocky
  - ../../../../base/keycloak
  - ../../../../base/nextcloud
  - ../../../../base/raspberry-pi-client
  - ../../../../base/raspberry-pi-server
  # - ../../../../base/hajimari
  # - ../../../../base/photoprism
  # - ../../../../base/uptime-kuma
  - ../../../../base/echo-server
  - ../../../../base/oauth2-proxy
  - ../../../../base/cloudnative-pg
  