---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/kube-vip
  - ../../../../base/metallb
  - ../../../../base/cert-manager
  - ../../../../base/metrics-server
  # - ../../../../base/wildcard-certificate
  - ../../../../base/ingress-nginx
  # - ../../../../base/longhorn
  # - ../../../../base/oauth2-proxy
  - ../../../../base/kubernetes-dashboard
  # - ../../../../base/echo-server
  # - ../../../../base/kured
  # - ../../../../base/reloader
  # - ../../../../base/reflector
  # - ../../../../base/system-upgrade
  # - ../../../../base/cloudnative-pg
  # - ../../../../base/pgadmin
  # - ../../../../base/keycloak
  # - ../../../../base/harbor
