---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/bjw-s
  - ../../../../base/metallb
  - ../../../../base/kube-vip
  - ../../../../base/uptime-kuma
  - ../../../../base/cert-manager
  - ../../../../base/oauth2-proxy
  - ../../../../base/ingress-nginx
  - ../../../../base/metrics-server
  - ../../../../base/wildcard-certificate
  - ../../../../base/kubernetes-dashboard
  - ../../../../base/nfs-subdir-external-provisioner
  - ../../../../base/primary-storage/nfs

  # - ../../../../base/hajimari
  # - ../../../../base/echo-server
  # - ../../../../base/kured
  # - ../../../../base/reloader
  # - ../../../../base/reflector
  # - ../../../../base/system-upgrade
  # - ../../../../base/cloudnative-pg
  # - ../../../../base/pgadmin
  # - ../../../../base/keycloak
  # - ../../../../base/harbor
