---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgadmin-charts
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/pgadmin/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/pgadmin/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: v1
  #     kind: Service
  #     # TODO: Figure out how to use variable substitution in here - @russell.green
  #     # Need to use ${POSTGRES_CLUSTER_NAME:=postgres-cluster}-rw and namespace.
  #     name: postgres-cluster-rw
  #     namespace: pgadmin
  # timeout: 10m
  dependsOn:
    - name: settings
    - name: pgadmin-charts
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
