---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgadmin-charts
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/pgadmin/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/pgadmin/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: pgadmin-pgadmin4
      namespace: pgadmin
  dependsOn:
    - name: settings
    - name: pgadmin-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
