---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudnative-pg-charts
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/cloudnative-pg/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Operator
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    # TODO: Figure out how to use variable substitution to set the namespaces below - @russell.green
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudnative-pg-operator
      namespace: cloudnative-pg
    - apiVersion: v1
      kind: Service
      name: cnpg-webhook-service
      namespace: cloudnative-pg
  dependsOn:
    - name: settings
    - name: cloudnative-pg-charts
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
