---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: false

    defaultSettings:
      defaultLonghornStaticStorageClass: longhorn
      # defaultDataPath: /mnt/storage
      replicaAutoBalance: "best-effort"
      dataLocality: "best-effort"
      numberOfReplicas: ${LONGHORN_STORAGE_REPLICAS:=3}
      storageMinimalAvailablePercentage: ${LONGHORN_STORAGE_MIN_PERCENTAGE:=15}
    ingress:
      enabled: ${LONGHORN_INGRESS_ENABLED:=true}
      host: "longhorn.${PRIMARY_DOMAIN}"
      tls: true
