---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${PRIMARY_DOMAIN/./-}"
  namespace: ${CERT_MANAGER_NAMESPACE:=cert-manager}
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "${CERT_REFLECT_NAMESPACES}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "${CERT_REFLECT_NAMESPACES}"
  secretName: "${PRIMARY_DOMAIN/./-}-tls"
  issuerRef:
    name: ${CERT_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "${PRIMARY_DOMAIN}"
  dnsNames:
    - "${PRIMARY_DOMAIN}"
    - "*.${PRIMARY_DOMAIN}"
