apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    additionalArguments:
      - "--entrypoints.websecure.http.tls"
      - "--providers.kubernetesIngress.ingressClass=traefik"
      - "--ping"
      - "--metrics.prometheus"
      - "--serversTransport.insecureSkipVerify=true"
      - "--api.insecure"
      - "--api.dashboard=true"

    deployment:
      enabled: true
      replicas: 2

    ingressRoute:
      dashboard:
        enabled: false

    service:
      spec:
        loadBalancerIP: "10.3.81.160" # this should be your Metal LB IP

    providers:
      kubernetesCRD:
        enabled: true
        # allowCrossNamespace: false
        allowExternalNameServices: true

      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true