apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app photoprism
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
spec:
  releaseName: *app
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    fullnameOverride: *app
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"
    image:
      repository: photoprism/photoprism
      tag: 221118-jammy
    env:
      ## See other config options from PhotoPrism documentation: https://docs.photoprism.org/getting-started/config-options/
      TZ: ${TIMEZONE}
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_SITE_URL: "https://photos.${PRIMARY_DOMAIN}/"
      PHOTOPRISM_SITE_TITLE: "Green's Photos"
      PHOTOPRISM_SITE_AUTHOR: "Rusty Green"
      PHOTOPRISM_APP_NAME: Photos
      PHOTOPRISM_ORIGINALS_LIMIT: 4000 # in MB (default 1000)
      # PHOTOPRISM_THUMB_FILTER: "blackman"
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      PHOTOPRISM_IMPORT_PATH: /photoprism/import
      # Database
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: "mariadb-mariadb-galera.photoprism.svc:3306"
      PHOTOPRISM_DATABASE_PASSWORD: "${PHOTOPRISM_MARIADB_PASSWORD}"
    service:
      main:
        ports:
          http:
            port: 2342
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          external-dns.alpha.kubernetes.io/target: "ipv4.${PRIMARY_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: image-multiple
        hosts:
          - host: &host photos.${PRIMARY_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism-config

      originals:
        enabled: true
        mountPath: /photoprism/originals
        existingClaim: photoprism-photos

      unsorted:
        enabled: true
        mountPath: /photoprism/import
        existingClaim: photoprism-photos-import
