---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-db
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
  annotations:
      nfs.io/storage-path: "photoprism-db"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ${PRIMARY_STORAGE_CLASS}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-config
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
  annotations:
      nfs.io/storage-path: "photoprism-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-photos
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
  annotations:
      nfs.io/storage-path: "photoprism-photos"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 950Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-photos-import
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
  annotations:
      nfs.io/storage-path: "photoprism-photos-import"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 500Gi
