---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: ${ZWAVE_JS_UI_NAMESPACE:=zwave-js-ui}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 8.8.4
    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            enabled: true
            port: &port 8091
          websocket:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host zwave.${PRIMARY_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        mountPath: /usr/src/app/store
        existingClaim: "zwave-js-ui-config"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
    resources:
      requests:
        memory: 100M
        cpu: 30m
      limits:
        memory: 512M
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-zwave
                  operator: In
                  values:
                    - "true"