---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hajimari-charts
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/hajimari/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hajimari
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/hajimari/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: hajimari
  #     namespace: hajimari
  dependsOn:
    - name: settings
    - name: hajimari-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
