---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NOTE: we're not including "git-repo-ssh-keys.sops.yaml" here because this file gets
  # added to the cluster during the bootstrapping process because it has to be there ahead
  # of time so that cluster SOPS can work properly.
  - git-repository.yaml
