---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: ${EMQX_NAMESPACE:=emqx}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.0.16
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 3
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_ADMIN_PASSWORD}
      EMQX_AUTH__USER__1__USERNAME: ${EMQX_USER}
      EMQX_AUTH__USER__1__PASSWORD: ${EMQX_PASSWORD}
    service:
      type: LoadBalancer
      loadBalancerIP: ${EMQX_IP}
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "EMQX"
          hajimari.io/icon: simple-icons:eclipsemosquitto
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${PRIMARY_DOMAIN}"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: false
    persistence:
      enabled: true
      storageClassName: ${EMQX_STORAGE:=local-path}
      size: 100Mi
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 512Mi
