---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://kubereboot.github.io/charts
      chart: kured
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
  values:
    configuration:
      startTime: "10pm"
      endTime: "2am"
      logFormat: "json"
      timeZone: "${TIMEZONE:=UTC}"
      rebootSentinelCommand: |-
        sh -c "! needs-restarting --reboothint"
