---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    usernameSecret:
      name: postgres-cluster-app
      key: username
    passwordSecret:
      name: postgres-cluster-app
      key: password
    host: postgres-cluster-rw.keycloak.svc
    database: keycloak
  hostname:
    hostname: identity.${PRIMARY_DOMAIN}
  http:
    tlsSecret: "${PRIMARY_DOMAIN/./-}-tls"
