---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    usernameSecret:
      name: postgres-app
      key: username
    passwordSecret:
      name: postgres-app
      key: password
    host: postgres-rw.keycloak.svc
    database: keycloak
  hostname:
    hostname: identity.${PRIMARY_DOMAIN}
  http:
    tlsSecret: primary-tls
  ingressSpec:
    foo