---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: ${UPTIME_KUMA_NAMESPACE:=uptime-kuma}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    global:
      nameOverride: *app
    image:
      # TODO: Add renovate - @russell.green
      repository: louislam/uptime-kuma
      tag: 1.19.6
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config
        mountPath: /app/data
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:alert-circle-check
        hosts:
          - host: &host "uptime.${PRIMARY_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
