---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: ${PGADMIN_NAMESPACE:=pgadmin}
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system
      interval: ${HELM_RELEASE_INTERVAL:=24h}
  values:
    env:
      email: "${SECRET_PGADMIN_USER}"
      password: "${SECRET_PGADMIN_PASSWORD}"

    strategy:
      type: Recreate

    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: "pgadmin.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "pgadmin.${SECRET_DOMAIN}"
