---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: ${PGADMIN_NAMESPACE:=pgadmin}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.13.6
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system
  values:
    env:
      email: "${PGADMIN_USER:=pgadmin@example.com}"
      password: "${PGADMIN_PASSWORD:=DONT_USE_DEFAULTS!}"

    strategy:
      type: Recreate

    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config

    ingress:
      enabled: true
      hosts:
        - host: "pgadmin.${PRIMARY_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "pgadmin.${PRIMARY_DOMAIN}"
