---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: ${PGADMIN_NAMESPACE:=pgadmin}
  annotations:
    nfs.io/storage-path: "pgadmin-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi
