---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: ${JELLYFIN_NAMESPACE:=jellyfin}
  annotations:
    nfs.io/storage-path: "jellyfin-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 75Gi
