---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ${MINIO_NAMESPACE:=minio}
  annotations:
    nfs.io/storage-path: "minio-data"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 25Gi
