---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: collabora
  namespace: ${COLLABORA_NAMESPACE:=collabora}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: collabora/code
      tag: 23.05.5.1.1
    
    env:
      extra_params: --o:ssl.termination=true --o:ssl.enable=false
    
    autoscaling:
      enabled: true
      target:  # deploymentname
      minReplicas:  1
      maxReplicas:  3
      targetCPUUtilizationPercentage:  80
      targetMemoryUtilizationPercentage:  80
  
    service:
      main:
        ports:
          http:
            port: 9980
    
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
          #ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16,10.0.0.0/8"
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
        - host: collabora.${PRIMARY_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - collabora.${PRIMARY_DOMAIN}