---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor-charts
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/harbor/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Database
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor-database
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/harbor/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: postgres-rw
      namespace: harbor
    - apiVersion: v1
      kind: Secret
      name: postgres-app
      namespace: harbor
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the harbor cluster.
      name: postgres-1
      namespace: harbor
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the harbor cluster.
      name: postgres-2
      namespace: harbor
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the harbor cluster.
      name: postgres-3
      namespace: harbor
  timeout: 10m
  dependsOn:
    - name: settings
    - name: cloudnative-pg-operator
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/harbor/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: keycloak-operator
  #     # TODO: Figure out how to use variable substitution in here - @russell.green
  #     namespace: keycloak
  timeout: 10m
  dependsOn:
    - name: settings
    - name: longhorn
    - name: harbor-charts
    - name: harbor-database
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
