---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raspberry-pi-server-basement
  namespace: ${RPI_SERVER_NAMESPACE:=raspberry-pi-server}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: pi-basement.${PRIMARY_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: raspberry-pi-server-basement
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - pi-basement.${PRIMARY_DOMAIN}
