apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mariadb
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
spec:
  releaseName: *app
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb-galera
      version: 7.4.12
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: photoprism-mariadb
    replicaCount: 3
    rootUser:
      user: photoprism
      password: ${PHOTOPRISM_ADMIN_PASSWORD}
    db:
      name: photoprism
      user: photoprism
      password: ${PHOTOPRISM_ADMIN_PASSWORD}
    persistence:
      enabled: true
      existingClaim: photoprism-db
    # auth:
    #   database: photoprism
    #   username: photoprism
    #   password: ${PHOTOPRISM_ADMIN_PASSWORD}
    # primary:
    #   extraFlags: --innodb-buffer-pool-size=2G --transaction-isolation=READ-COMMITTED --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    #   persistence:
    #     enabled: true
    #     existingClaim: photoprism-db
    # secondary:
    #   replicaCount: 2
