---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-db
  namespace: ${PHOTOPRISM_NAMESPACE:=photoprism}
  annotations:
      nfs.io/storage-path: "photoprism-db"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${MARIADB_STORAGE_CLASS}
