# Proxy service/ingress for homelab proxmox server.
# Adding this allows accessing the proxmox server over a valid
# HTTPS certificate through ingress (when on the network).
---
kind: Service
apiVersion: v1
metadata:
  name: proxmox
  namespace: default
spec:
  type: ExternalName
  # IP: 192.168.6.9
  externalName: node-1
  ports:
  - name: https
    port: 443
    targetPort: 8006
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol:  "HTTPS"
    hajimari.io/group: Homelab Infrastructure
    hajimari.io/appName: Proxmox Server
    hajimari.io/icon: mdi:presentation
spec:
  rules:
  - host: "proxmox.${PRIMARY_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxmox
            port:
              name: https
