---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: settings
  namespace: flux-system
spec:
  interval: 1h
  # NOTE: "path" must be patched
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: flux-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
