---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # NOTE: "path" must be patched
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: calico-typha
      namespace: calico-system
    - apiVersion: apps/v1
      kind: Deployment
      name: calico-kube-controllers
      namespace: calico-system
    - apiVersion: apps/v1
      kind: Deployment
      name: coredns
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: local-path-provisioner
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: tigera-operator
      namespace: tigera-operator
  decryption:
    provider: sops
    secretRef:
      name: sops-age
