---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/rustygreen/gitops
  secretRef:
    name: git-ssh-keys
