---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/homelab/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
