---
# Git repository patches
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  ref:
    branch: main
---
# Cluster patches
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  path: ./clusters/homelab/production
---
# Cluster setting patches
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: settings
  namespace: flux-system
spec:
  path: ./clusters/homelab/production/settings
