---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL:=1h}
  url: https://stakater.github.io/stakater-charts
