---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 3.4.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      # https://hub.docker.com/_/nextcloud
      repository: docker.io/library/nextcloud
      tag: 24.0.6-fpm
    env:
      TZ: "${TIMEZONE}"
      NEXTCLOUD_ADMIN_USER:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: ADMIN_USERNAME
      NEXTCLOUD_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: ADMIN_PASSWORD
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${PUBLIC_DOMAIN}"
      SMTP_HOST: maddy.comms.svc.cluster.local
      SMTP_PORT: 2525
      SMTP_AUTHTYPE: PLAIN
      MAIL_FROM_ADDRESS: "${SMTP_USER}"
      POSTGRES_HOST: nextcloud-postgres.default.svc.cluster.local
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: POSTGRES_PASSWORD
      REDIS_HOST: nextcloud-redis.default.svc.cluster.local
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: REDIS_PASSWORD
      NEXTCLOUD_DATA_DIR: /data
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    persistence:
      data:
        enabled: true
        existingClaim: appdata
        subPath:
          - path: nextcloud/html
            mountPath: /var/www/html
          - path: nextcloud/data
            mountPath: /data
          # https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212
          - path: nextcloud/redis-session.ini
            mountPath: /usr/local/etc/php/conf.d/redis-session.ini
      redis-config:
        enabled: true
        mountPath: /var/www/html
        existingClaim: appdata
        subPath: nextcloud
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-outline
        hosts:
          - host: &host "cloud.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
