---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 3.5.9
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  # See https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml
  values:
    # TODO: Re-evaluate the following sources:
    # https://github.com/ishioni/homelab-ops/blob/master/cluster/apps/fileservers/nextcloud/helmrelease.yaml
    # https://github.com/angelnu/k8s-gitops/blob/main/apps/default/nextcloud/release.yaml
    image:
      repository: rustygreen/nextcloud
      tag: 26.0.2
    hpa:
      enabled: true
      cputhreshold: 60
      minPods: 2
      maxPods: 5
    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: Nextcloud
        hajimari.io/icon: simple-icons:nextcloud
        hajimari.io/info: File and Calendar server
        hajimari.io/group: tools
        nginx.ingress.kubernetes.io/proxy-body-size: "16G"
        nginx.ingress.kubernetes.io/custom-http-errors: "418"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
        
          # Rule borrowed from .htaccess to handle Microsoft DAV clients
          location = / {
            if ( $http_user_agent ~ ^DavClnt ) {
              return 302 /remote.php/webdav/$is_args$args;
            }
          }

          location = /robots.txt {
              allow all;
              log_not_found off;
              access_log off;
          }

          location ^~ /.well-known {
          
            # The rules in this block are an adaptation of the rules
            # in .htaccess that concern /.well-known.

            location = /.well-known/carddav { return 301 /remote.php/dav/; }
            location = /.well-known/caldav  { return 301 /remote.php/dav/; }
            
            location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
            location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
            
            # Let Nextcloud's API for /.well-known URIs handle all other
            # requests by passing them to the front-end controller.
            return 301 /index.php$request_uri;
          }
          
          # Rules borrowed from .htaccess to hide certain paths from clients
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }

          # Rule borrowed from .htaccess
          #location /remote {
          #    return 301 /remote.php$request_uri;
          #}
      tls:
      - hosts:
        - &host cloud.${PRIMARY_DOMAIN}
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      database: nextcloud
      host: postgres-rw.nextcloud.svc:5432
      existingSecret:
        enabled: true
        secretName: postgres-app
        usernameKey: username
        passwordKey: password
    cronjob:
      enabled: true
      failedJobsHistoryLimit: 10
      successfulJobsHistoryLimit: 10
    nextcloud:
      host: *host
      username: ${NEXTCLOUD_USERNAME:=admin}
      password: ${NEXTCLOUD_PASSWORD:=changeme}
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
          default_phone_region = US
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => 
            array(
              0 => '${NETWORK_K8S_CLUSTER_CIDR}',
            ),
            'forwarded_for_headers' => 
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'default_phone_region' => 'US',
            'enabledPreviewProviders' =>
            array (
              0 => 'OC\\Preview\\PNG',
              1 => 'OC\\Preview\\JPEG',
              2 => 'OC\\Preview\\GIF',
              3 => 'OC\\Preview\\HEIC',
              4 => 'OC\\Preview\\BMP',
              5 => 'OC\\Preview\\XBitmap',
              6 => 'OC\\Preview\\MP3',
              7 => 'OC\\Preview\\TXT',
              8 => 'OC\\Preview\\MarkDown',
              9 => 'OC\\Preview\\OpenDocument',
              10 => 'OC\\Preview\\Krita',
              11 => 'OC\\Preview\\MOV',
            ),
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_button_text' => 'Log in with OpenID',
            'oidc_login_hide_password_form' => false,
            'oidc_login_disable_registration' => false,
            'oidc_create_groups' => true,
            'oidc_login_webdav_enabled' => true,
            'oidc_login_password_authentication' => false,
            'oidc_login_client_id' => '${NEXTCLOUD_OIDC_CLIENT_ID:=nextcloud}',
            'oidc_login_client_secret' => '${NEXTCLOUD_OIDC_CLIENT_SECRET}',
            'oidc_login_provider_url' => '${NEXTCLOUD_OIDC_SERVER}',
            'oidc_login_end_session_redirect' => true,
            'oidc_login_logout_url' => 'https://cloud.${PRIMARY_DOMAIN}/apps/oidc_login/oidc',
            'oidc_login_auto_redirect' => true,
            'oidc_login_redir_fallback' => true,
            'oidc_login_code_challenge_method' => 'S256',
            'oidc_login_attributes' => 
            array (
              'id' => 'preferred_username',
              'mail' => 'email',
            ),
          );
        gitops.config.php: |-
          <?php
          $CONFIG = array (
            'appstoreenabled' => true,
            #'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
            'mail_domain' => '${PRIMARY_DOMAIN}',
          );
        # Circumvention for client freezes - https://github.com/nextcloud/desktop/issues/5094
        # TODO: Remove this once fixed - @russell.green
        bulkupload.config.php: |-
          <?php
          $CONFIG = array (
            'bulkupload.enabled' => false,
          );
    persistence:
      enabled: true
      existingClaim: nextcloud
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false