---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
      nfs.io/storage-path: "nextcloud-data"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 950Gi
