---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: ${HOME_ASSISTANT_NAMESPACE:=home-assistant}
  annotations:
    nfs.io/storage-path: "home-assistant-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 5Gi
