---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL:=1h}
  url: https://charts.jetstack.io/
