# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-settings
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:x+TLCjIl+FMy27NDSXfjtQ==,iv:xlph7gwRCZ8zbWaCMLnyLCQHu3lVdqAr3izrYbueKFg=,tag:E5TyVqnDAKWrgQW1qrM6eQ==,type:str]
    INGRESS_CLASS: ENC[AES256_GCM,data:Y3Sk2kM=,iv:Dx8d8nFs6xQNdn8IiMGvXfngN91qGtmBWbQwSApZq/c=,tag:xRGlt58UaCDdjwhanGlGmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHlKeTVOcnpjSEplVU96
            US91dkh4bUxvRGdiby9jOUN5ekR4Zi9RQzF3CkNnWWRCY0NVOGExT2Z3RFIwRlRM
            SFh0ZnJMYnNCclRadTlPNXZ5dGovVE0KLS0tIC9mSzN0Lzk0Q2xhL0EzY1pnTUlX
            dFcvcDJtaktiREFiZU4xQ0lkbXE1eTQKwX9HGFeQVm1zq19vs2RbIqdUCCqLaQ9F
            qHpnGHg1JTZZ5mV7IzyB0k/N843N5ss26S4pE5E8mdzMFTjvndM2qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-25T21:04:41Z"
    mac: ENC[AES256_GCM,data:mX/c6G44wFL4L3SWk/HJe/MahF57cFbqbQdIIAtcsl1QVp7vRTGEfdZ735QQ4DiP30qnCGesbTB6P0N7Z4PxsEIHBQU9eCJwyZFegGuAwi78B21adB57YczRFjV/ha/w51YtPvIfmeY5lVci8sRh2XXxmhpf5bUsdl26MCcG51w=,iv:YE/3PJUVg9N/wo+DPlRXWhUOgXkyCkd7d42bkiftGlc=,tag:nAcZ1Du/oiRiqa+FLskkJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
