---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: ${CLOUDNATIVE_PG_NAMESPACE:=cloudnative-pg}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    crds:
      create: true
    # config:
    #   data:
    #     INHERITED_ANNOTATIONS: kyverno.io/ignore
    # image:
    #   repository: ghcr.io/cloudnative-pg/cloudnative-pg-testing
    #   tag: main
