---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: ${EXCALIDRAW_NAMESPACE:=excalidraw}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: docker.io/excalidraw/excalidraw
      tag: latest@sha256:e1275b283b1045d97648505afeeeb47fba7b5f1c33f1be3fcf3dc9f0f1399d7f

    service:
      main:
        ports:
          http:
            port: 8080
            targetPort: 80

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_RECORD_NAME}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/appName: Draw
          hajimari.io/icon: mdi:draw
        hosts:
          - host: &host "draw.${PRIMARY_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 128M
