---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emqx-charts
  namespace: flux-system
spec:
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./base/emqx/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emqx
  namespace: flux-system
spec:
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./base/emqx/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: emqx-emqx
  #     namespace: emqx
  dependsOn:
    - name: settings
    - name: emqx-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
