---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL}
  url: https://cloudnative-pg.github.io/charts
