---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ${NGINX_NAMESPACE:=nginx}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      chart: ingress-nginx
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: ${HELM_RELEASE_INTERVAL:=24h}
  dependsOn:
    - name: cert-manager
      namespace: ${CERT_MANAGER_NAMESPACE:=cert-manager}
  values:
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE:=UTC}"
      service:
        annotations:
          # TODO: Figure out how to omit this or set a better default - @russell.green
          metallb.universe.tf/loadBalancerIPs: |-
            ${METALLB_INGRESS_ADDR:=0.0.0.0}
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: |-
          ${CUSTOM_HTTP_ERRORS:=401,403,404,500,501,502,503}
        enable-brotli: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/${PRIMARY_DOMAIN/./-}-tls"
      podAnnotations:
        configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.18.0
      replicaCount: ${INGRESS_REPLICA_COUNT:=2}
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
  valuesFrom:
    # Cloudflare Networks
    # https://www.cloudflare.com/ips/
    - targetPath: controller.config.proxy-real-ip-cidr
      kind: ConfigMap
      name: cloudflare-proxied-networks
      valuesKey: cloudflare-proxied-networks.txt
