---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ${NGINX_NAMESPACE:=nginx}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      chart: ingress-nginx
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: ${HELM_RELEASE_INTERVAL:=24h}
  values:
    controller:
      replicaCount: ${INGRESS_REPLICA_COUNT:=2}
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE:=UTC}"
      service:
        annotations:
          service.beta.kubernetes.io/azure-dns-label-name: ${AZURE_DNS_LABEL:=""}
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
          service.beta.kubernetes.io/azure-load-balancer-resource-group: ${AZURE_RESOURCE_GROUP:=""}
        externalTrafficPolicy: Local
        loadBalancerIP: ${LOAD_BALANCER_IP:=""}
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        # TODO: Revisit these: change to 16k
        client-header-buffer-size: "512k"
        large-client-header-buffers: "4 512k"
        proxy-buffer-size: "512k"
        custom-http-errors: ${CUSTOM_HTTP_ERRORS:=401,403,404,500,501,502,503}
        enable-brotli: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
        force-ssl-redirect: "${INGRESS_FORCE_SSL:=true}"
      metrics:
        enabled: false
      extraArgs:
        default-ssl-certificate: "${CERT_MANAGER_NAMESPACE:=cert-manager}/primary-tls"
      podAnnotations:
        configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.19.0
      replicaCount: ${INGRESS_BACKEND_REPLICA_COUNT:=1}
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ${INGRESS_BACKEND_TEMPLATE:='lost-in-space'}
        - name: SHOW_DETAILS
          value: ${INGRESS_BACKEND_SHOW_DETAILS:='false'}
  valuesFrom:
    # Cloudflare Networks
    # https://www.cloudflare.com/ips/
    - targetPath: controller.config.proxy-real-ip-cidr
      kind: ConfigMap
      name: cloudflare-proxied-networks
      valuesKey: cloudflare-proxied-networks.txt
