---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jelllyfin
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/jellyfin/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  # healthChecks:
  #   - apiVersion: v1
  #     kind: Secret
  #     name: jelllyfin-secret
  #     namespace: jelllyfin
  #   - apiVersion: batch/v1
  #     kind: CronJob
  #     name: jelllyfin
  #     namespace: jelllyfin
  dependsOn:
    - name: settings
    - name: bjw-s-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
