---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: &namespace ${RELOADER_NAMESPACE:=reloader}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  # renovate: registryUrl=https://stakater.github.io/stakater-charts
  chart:
    spec:
      chart: reloader
      version: v1.0.1
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    fullnameOverride: reloader
    reloader:
      reloadStrategy: annotations
      podMonitor:
        enabled: true
        namespace: *namespace
