---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL:=1h}
  url: https://kubernetes.github.io/ingress-nginx
