---
# Cluster patches
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  path: ./clusters/homelab/development
---
# Cluster setting patches
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: settings
  namespace: flux-system
spec:
  path: ./clusters/homelab/development/settings
---
# Override database settings.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cloudnative-pg
spec:
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: postgres-keycloak
