apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: keycloak
spec:
  instances: 3
  storage:
    size: 50Gi
    storageClass: ${POSTGRES_STORAGE_CLASS:=''}
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  monitoring:
    enablePodMonitor: true
