---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspberry-pi-client
  namespace: ${RPI_CLIENT_NAMESPACE:=raspberry-pi-client}
spec:
  selector:
    matchLabels:
      app: raspberry-pi-client
  replicas: 1
  template:
    metadata:
      labels:
        app: raspberry-pi-client
    spec:
      containers:
        - name: raspberry-pi-client
          image: ghcr.io/rustygreen/raspberry-pi-client:main
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          env:
            - name: RPC_CONFIG
              value: |-
                {
                  "servers": [
                    {
                      "title": "Basement RPi",
                      "url": "https://pi-basement.${PRIMARY_DOMAIN}",
                      "hideUnlabeled": true,
                      "pinLabels": {
                        "40": "Chickens water",
                        "33": "Cows water",
                        "35": "Main water supply",
                        "37": "Main water drain"
                      }
                    },
                    {
                      "title": "Cowport RPi",
                      "url": "https://pi-cowport.${PRIMARY_DOMAIN}",
                      "hideUnlabeled": true,
                      "pinLabels": {
                        "16": "Water Sensor Trigger",
                        "18": "Water Sensor Echo",
                        "11": "Open Valve (alone) & Power On",
                        "13": "Close Valve (13 + 15)",
                        "15": "Close Valve (13 + 15)"
                      }
                    }
                  ]
                }
