---
# Charts
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-charts
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/cert-manager/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Controller
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: cert-manager-charts
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Cluster Issuers
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: cert-manager-charts
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
