---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: keycloak
spec:
  # See: https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
  schedule: "@midnight"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres
