---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: homelab-proxied-sites
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/homelab-proxied-sites/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
    - name: ingress-nginx
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
