---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./clusters/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
