---
# Workloads
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/adguard/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: adguard
      namespace: adguard
  dependsOn:
    - name: settings
    - name: bjw-s-charts
    - name: primary-storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
