---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: ${ADGUARD_NAMESPACE:=adguard}
  annotations:
    nfs.io/storage-path: "adguard-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PRIMARY_STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi
