---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: ${BLOCKY_NAMESPACE:=blocky}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: spx01/blocky
      tag: v0.20

    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 3

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        type: configMap
        name: &config blocky-config
        subPath: config.yml
        mountPath: /app/config.yml
        readOnly: true

    configMaps:
      config:
        enabled: true
        data:
          config.yml: |-
            upstream:
              default:
                - tcp+udp:10.0.1.1
            conditional:
              mapping:
                ${PRIMARY_DOMAIN}: tcp+udp:${LOAD_BALANCER_IP}
            customDNS:
              mapping:
                ${PRIMARY_DOMAIN}: ${LOAD_BALANCER_IP}
            blocking:
              blackLists:
                ads:
                - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
                - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                - http://sysctl.org/cameleon/hosts
                - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
                cookies:
                - https://www.fanboy.co.nz/fanboy-cookiemonster.txt
              whiteLists:
                ads:
                - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                - https://raw.githubusercontent.com/rust84/k8s-gitops/main/k8s/clusters/cluster-0/manifests/network/blocky/whitelist.txt
              clientGroupsBlock:
                default:
                - ads
                  # - special
            clientLookup:
              upstream: tcp+udp:10.0.1.1
            prometheus:
              enable: true
              path: /metrics
            httpPort: 4000
            logLevel: info
    service:
      main:
        enabled: true
        ports:
          http:
            port: 4000
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_BLOCKY_ADDRESS}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
          dns-dot:
            enabled: true
            port: 853
            protocol: TCP
            targetPort: 853
          dns-https:
            enabled: true
            port: 443
            protocol: TCP
            targetPort: 443

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi