---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: ${BLOCKY_NAMESPACE:=blocky}
spec:
  interval: ${HELM_RELEASE_INTERVAL:=24h}
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: spx01/blocky
      tag: v0.21

    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 3

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        type: configMap
        name: &config blocky-config
        subPath: config.yml
        mountPath: /app/config.yml
        readOnly: true

    configMaps:
      config:
        enabled: true
        data:
          config.yml: |-
            upstream:
              default:
                - 1.1.1.3
                - 1.0.0.3
            conditional:
              mapping:
                ${PRIMARY_DOMAIN}: tcp+udp:${LOAD_BALANCER_IP}
            customDNS:
              mapping:
                ${PRIMARY_DOMAIN}: ${LOAD_BALANCER_IP}
            blocking:
              blackLists:
                suspicious:
                  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
                  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
                  - https://v.firebog.net/hosts/static/w3kbl.txt
                ads:
                  - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
                  - |
                    /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
                    /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
                    /^(.+[_.-])?telemetry[_.-]/
                    /^adim(age|g)s?[0-9]*[_.-]/
                    /^adtrack(er|ing)?[0-9]*[_.-]/
                    /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
                    /^aff(iliat(es?|ion))?[_.-]/
                    /^banners?[_.-]/
                    /^beacons?[0-9]*[_.-]/
                    /^count(ers?)?[0-9]*[_.-]/
                    /^mads\./
                    /^pixels?[-.]/
                    /^stat(s|istics)?[0-9]*[_.-]/
                trackers:
                  - https://v.firebog.net/hosts/Easyprivacy.txt
                  - https://v.firebog.net/hosts/Prigent-Ads.txt
                  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
                  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
                  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
                misc:
                  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
                  - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
                  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
                  - https://v.firebog.net/hosts/Prigent-Crypto.txt
                  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
                  - https://phishing.army/download/phishing_army_blocklist_extended.txt
                  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
                  - https://v.firebog.net/hosts/RPiList-Malware.txt
                  - https://v.firebog.net/hosts/RPiList-Phishing.txt
                  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
                  - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
              whiteLists:
                suspicious:
                  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                ads:
                  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                trackers:
                  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                misc:
                  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
              clientGroupsBlock:
                default:
                  - suspicious
                  - ads
                  - trackers
                  - misc
            prometheus:
              enable: true
              path: /metrics
            httpPort: 4000
            logLevel: info
    service:
      main:
        enabled: true
        ports:
          http:
            port: 4000
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${BLOCKY_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
          dns-dot:
            enabled: true
            port: 853
            protocol: TCP
            targetPort: 853
          dns-https:
            enabled: true
            port: 443
            protocol: TCP
            targetPort: 443

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi