---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: ${HELM_REPOSITORY_INTERVAL:=1h}
  url: https://helm.runix.net
