---
# CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/keycloak/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Operator
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/keycloak/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: keycloak-operator
      # TODO: Figure out how to use variable substitution in here - @russell.green
      namespace: keycloak
  timeout: 10m
  dependsOn:
    - name: settings
    - name: keycloak-crds
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Database
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-database
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/keycloak/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: postgres-cluster-rw
      namespace: keycloak
    - apiVersion: v1
      kind: Secret
      name: postgres-cluster-app
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-cluster-1
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-cluster-2
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-cluster-3
      namespace: keycloak
  timeout: 10m
  dependsOn:
    - name: settings
    - name: cloudnative-pg-operator
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1h
  path: ./base/keycloak/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: keycloak-service
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-0
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-1
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-2
      namespace: keycloak
  timeout: 15m
  dependsOn:
    - name: settings
    - name: keycloak-crds
    - name: keycloak-operator
    - name: keycloak-database
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
