---
# Dependencies
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-dependencies
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/keycloak/dependencies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
      # NOTE: we are waiting for the certificate to be replicated to the "keycloak" namespace
      # because we don't want to proceed with keycloak installation unless we have the wildcard
      # certificate in this namespace. "reflector" is used to replicate to the keycloak namespace.
    - apiVersion: v1
      kind: Secret
      name: primary-tls
      namespace: keycloak
  dependsOn:
    - name: settings
    - name: wildcard-certificate
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./base/keycloak/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: settings
    - name: keycloak-dependencies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Operator
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 10m
  path: ./base/keycloak/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: keycloak-operator
      # TODO: Figure out how to use variable substitution in here - @russell.green
      namespace: keycloak
  dependsOn:
    - name: settings
    - name: keycloak-crds
    - name: keycloak-dependencies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Database
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-database
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 10m
  path: ./base/keycloak/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: postgres-rw
      namespace: keycloak
    - apiVersion: v1
      kind: Secret
      name: postgres-app
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-1
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-2
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: postgres-3
      namespace: keycloak
  dependsOn:
    - name: settings
    - name: cloudnative-pg-operator
    - name: keycloak-dependencies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
# Cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 10m
  path: ./base/keycloak/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: keycloak-service
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-0
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-1
      namespace: keycloak
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: keycloak-2
      namespace: keycloak
  dependsOn:
    - name: settings
    - name: keycloak-dependencies
    - name: keycloak-crds
    - name: keycloak-operator
    - name: keycloak-database
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
